kind = "api"
previewPath = "/api"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api"]

[services.development]
run = "mvn --file /home/runner/workspace/artifacts/api-server/pom.xml spring-boot:run"

[services.production]

[services.production.build]
args = ["mvn", "--file", "/home/runner/workspace/artifacts/api-server/pom.xml", "package", "-DskipTests"]

[services.production.run]
args = ["java", "-jar", "/home/runner/workspace/artifacts/api-server/target/smartcare-api-1.0.0.jar"]

[services.production.run.env]
PORT = "8080"

[services.production.health.startup]
path = "/api/healthz"
